stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE_NAME .
  tags:
    - docker

deploy:
  stage: deploy
  image: python:2
  script:
    - pip install ssh-deploy
    - ssh-deploy --hosts $LOCAL_MACHINE_IP --username username --private-key /path/to/private/key /path/to/nginx.conf /etc/nginx/nginx.conf
    - ssh username@$LOCAL_MACHINE_IP "docker pull $DOCKER_IMAGE_NAME"
    - ssh username@$LOCAL_MACHINE_IP "docker stop $DOCKER_CONTAINER_NAME || true && docker rm $DOCKER_CONTAINER_NAME || true"
    - ssh username@$LOCAL_MACHINE_IP "docker run --name $DOCKER_CONTAINER_NAME --publish 80:80 $DOCKER_IMAGE_NAME"
  environment:
    name: production
  only:
    - master
